### ISSUE TITLE
multi select by mouse? 

### ISSUE THREAD

**Issue by cissusnar** [TheNounProject/CollectionView#17]
Does CollectionView support multi select by mouse ?

**Comment by WCByrne** [comment]
You can multi select with cmd/shift click. Drag to select (like desktop) is not built in but can be added pretty trivially at the controller level in `mouseDragged`. I can dig up some example code if you need it.

**Comment by cissusnar** [comment]
Multi select by mouse is built in NSCollectionView, but NSCollectionView is very very ... you know.
